### ISSUE TITLE
How to view the generated task sequences?

### ISSUE THREAD

**Issue by Ravindu-Yasas-Nagasinghe** [MCG-NJU/PDPP#4]
First, thank you for the repo and the support. I successfully implemented the code. 

I want to find the generated tasks for each video_id. Your code only outputs acc , mIOU etc. If I want to find out the task sequences generated. How do I do that.

 Also , if I want to find the tasks for my own video (to test with own data), how do I do that?

**Comment by pPetrichor** [comment]
Hi, sorry for the late reply. To find the generated action sequences, you can extract the action dimensions from the model output to get the predicted action ids(use argmax). The correspondence between action content and id can be found in 'dataset/crosstask/actions_onehot.npy'. The keys in this file have a format like 'task id_action num'(For example, '23521_0' means the first action in task 'Make Jello Shots', which is 'pour water'). So you can get the action sequence content in this way.

If you want to apply PDPP to your own data, you can provide the video clip features to the model and find the predicted task class first. Take Crosstask as example, the correspondence between task and task id is available in 'data_load_mlp.py(line 100)'. The you can further get the action sequence as mentioned above.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
Hi @pPetrichor , thank you for your reply . can you please tell me how I can do this ' you can extract the action dimensions from the model output' and where I can find the model output?

Also in the 'dataset/crosstask/actions_onehot.npy' file, we get a sequence like {'71781_7': 17,........}. Here as you mentioned 71781 is task id and _7 is the action num. Then what is 17. Is it action content?

Also do you store the language descriptions for each action some where . Ex: '23521_0' is 'pour water'.

**Comment by pPetrichor** [comment]
The output is the concatenation of actions and planning conditions, which you can read the paper to get details. So actions can be get like 'actions_pred = actions_pred[:, :, args.class_dim:args.class_dim + args.action_dim].contiguous()' in inference.py line 111. The model output is just the forward result of the saved model? Maybe you could read the paper and inference codes to get the answer.

17 is the action id. In crosstask, there are 105 different actions so the action prediction result is 105-dim vector. If 17 is the argmax id, then the planning result for current action is 71781_7. 

The language descriptions for each action is in Crosstask dataset. 'task_primary.txt'.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
Hi, thank you for the help. 
Yes, I have read the paper and according to it the action pred dimensions should be [T, 3, 105] but when I find the dimensions of action pred from your code, it gives [128, 3, 105]. Since , T = 3. How is this possible. 
 Sorry for my confusion.  
Also I tried to view the model output saved in save_max but I was not able to open .pth or .pkl files which gives an error. Thank you for your help in advance.

**Comment by pPetrichor** [comment]
The shape of the output action pred dimensions should be [bs, T, action_dim], so maybe 128 is your evaluation batch size, which means you get 128 predicted planning action sequences.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
Thank you very much for the support.
