### ISSUE TITLE
Viewing input image frames

### ISSUE THREAD

**Issue by Ravindu-Yasas-Nagasinghe** [MCG-NJU/PDPP#6]
I got all the action sequences in the validation (infrernce.py) code inn text format. Now I want to find out which action sequence is related to which image frames or which [input, goal] video pair . For this I suppose I need to view the following vid . For example: 

{'vid': 'W0587ftyNsU', 'task': '91515', 'feature': '/l/users/ravindu.nagasinghe/datasets/PDPP/CrossTask_assets/processed_data/91515_W0587ftyNsU.npy', 'legal_range': [[334, 358, 102], [403, 407, 103], [423, 434, 103]], 'task_id': 17, 'event_class': 17}

How do I view this  as image frames or video clippings?

If I view in task wise it does not gives the exact cropped version of video used for each sequence. So I need to view image frames for each vid in different legal ranges for each action sequence.  How Do I do that?

**Comment by pPetrichor** [comment]
Maybe you can just search the 'W0587ftyNsU' video on YouTube and get the video clip according to the start time and end time for each action. For example, the time period for action 102 is 334s-358s. Since it is the start action, then the start observation is a 3-seconds clip starting from 334s.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
Thank you very much for the answer.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
what is the frame rate you used in input and goal videos? (How many image frames  per video you used? ex: number of frames used in the code out of  [334, 358, 102] part of video?). Where can we configure this in the code? (change the number of frames used?) Is the start and end video lengths 3 seconds? (Are these obtained directly as features from the dataset unlike obtaining the videos and then splicing into different vids and then getting image frames and then features ?)

**Comment by pPetrichor** [comment]
Hi, we just use the features provided by P3IV(https://github.com/JoeHEZHAO/procedure-planing), so you can go to verify the feature extraction code there.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
sure, thanks
